---

- name: Add nexcloud chart repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: "https://charts.longhorn.io"

- name: Deploy longhorn
  kubernetes.core.helm:
    name: longhorn
    state: present
    chart_ref: longhorn/longhorn
    chart_version: 1.3.2
    values: "{{ lookup('file', 'files/values.yaml') | from_yaml  }}"
    release_namespace: longhorn-system
    create_namespace: true
    
- name: Deploy Ingress
  kubernetes.core.k8s:
    state: present
    namespace: longhorn-system
    src: files/longhorn-ingress.yaml

    
- name: Deploy longhorn-2 storage class
  kubernetes.core.k8s:
    state: present
    namespace: longhorn-system
    src: files/tworeplica.yaml

    
- name: Deploy longhorn-3 storage class
  kubernetes.core.k8s:
    state: present
    namespace: longhorn-system
    src: files/threereplica.yaml
