---
# tasks file for jenkins
- name: Add chart repo
  kubernetes.core.helm_repository:
    name: jenkins
    repo_url: "https://charts.jenkins.io"

- name: Deploy Jenkins instance
  kubernetes.core.helm:
    name: jenkins
    state: present
    chart_ref: jenkins/jenkins
    chart_version: 4.2.15
    values: "{{ lookup('file', 'values.yaml') | from_yaml  }}"
    release_namespace: jenkins
    create_namespace: true