apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-bazooka-precious
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: kubernetes.io/hostname
        value: "klucsik-bazooka"
      - name: BasePath
        value: /data/Precious1g
provisioner: openebs.io/local
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer