apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-storage
spec:
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: longhorn-2
        resources:
          requests:
            storage: 20Gi