- name: Add chart repo
  kubernetes.core.helm_repository:
    name: requarks
    repo_url: "https://charts.js.wiki"

- name: Deploy Wiki instance
  kubernetes.core.helm:
    name: wiki
    state: present
    chart_ref: requarks/wiki
    chart_version: 2.2.0
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml  }}"
    release_namespace: '{{ instance_name }}-wiki'
    create_namespace: true

- name: Deploy postgresql-db
  kubernetes.core.k8s:
    state: present
    namespace: '{{ instance_name }}-wiki'
    template: templates/psql-deployment.yaml.j2